config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "works#index"

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :works, only: [:index, :show, :create] do
    resources :wages, only: [:show, :create]
    resource :comments, only: :create
  end
  resources :users, only: :show

end

app/models/user.rb
class User < ApplicationRecord
  has_many :works
  has_many :wages
  has_many :comments

  with_options presence: true do
    validates :username
    validates :email
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @time = Time.zone.now

    @user = User.find(params[:id])
    @work = Work.order(id: :DESC).find_by(user_id: @user.id)
    @wage = @user.wages.find_by(work_id: @work.id) if @user.wages != []

    @wages = Wage.order(id: :DESC).where(user_id: @user.id)
    @comments = Comment.order(id: :DESC).where(user_id: @user.id)
  end
end

app/views/users/show.html.erb
<div class="main">

  <div class="left_bar">
    <h1>精鋭部隊</h1>

    <div class="log_in">
        <%= link_to current_user.username, user_path(id: current_user.id), class: "username" %>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %>
    </div>
      <%= link_to 'topへ戻る', root_path %>
      <%if @wage == nil && @work != nil %>
        <%= link_to '仕事中', work_path(@work.id) %>
      <%end%>
  </div>

  <div class="right_bar">
    <H2><%= "#{@user.username}さんのページ" %></h2>
    <div id="day" class="day">
      <%= "#{@time.year}年#{@time.month}月#{@time.day}日" %>
      <div id="time" class="time">
      </div>
    </div>
    <% if @user.wages %>
      <% @month = 0 %>
      <% @wages.each do |w| %>
        <div class="wage">
          <%= "#{w.created_at.strftime('%Y/%m/%d')}" %>
          <%= "#{w.end_time}時間" %>
          <%= "#{w.paying}円" %>
        </div>
        <% @month += w.paying %>
      <% end %>
      <div class="sum">
        <%= "月合計 #{@month}円"%>
      </div>
    <% end %>

    <% if @comments %>
      <% @comments.each do |c| %>
        <div id='comments' class="comments">
          <p>
            <%= "#{c.created_at.strftime('%Y/%m/%d')}" %><br>
            <% if @user.id == 1 %>
              <%= "#{c.work.user.username}さんへ"%><br>
            <% end %>
            <%= "#{c.user.username}:"%>
            <%= c.text %>
          </p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>